import type { Song, Artist, Testimonial, Genre, Notification, AdminUser, AdminCampaign, ChartData } from "@/src/types";

export const mockSongs: Song[] = [
  {
    id: "1",
    slug: "afrobeats-in-the-rain",
    title: "Afrobeats in the Rain",
    artist: "Kofi Mensah",
    artistId: "kofi-mensah",
    artistAvatar: "https://i.pravatar.cc/150?img=11",
    coverArt: "https://picsum.photos/seed/afro1/400/400",
    genre: "Afrobeats",
    description: "A soulful blend of traditional Ghanaian rhythms with modern Afrobeats production.",
    story: "This song was born during the rainy season in Accra. I sat by my window watching the rain fall on the red earth and felt the ancestors speaking through the rhythm. I want to share this feeling with the world.",
    fundingGoal: 500000,
    amountRaised: 387500,
    supporters: 1243,
    daysLeft: 12,
    deadline: "2026-06-07",
    status: "active",
    tags: ["afrobeats", "ghana", "rain", "soul"],
    topSupporters: [
      { id: "s1", name: "Amara Diallo", avatar: "https://i.pravatar.cc/150?img=1", amount: 25000, message: "This is fire!", date: "2026-05-20" },
      { id: "s2", name: "Tunde Bakare", avatar: "https://i.pravatar.cc/150?img=2", amount: 15000, date: "2026-05-19" },
      { id: "s3", name: "Zara Osei", avatar: "https://i.pravatar.cc/150?img=3", amount: 10000, message: "Keep creating!", date: "2026-05-18" },
    ],
    recentActivity: [
      { id: "a1", type: "support", user: "Amara Diallo", avatar: "https://i.pravatar.cc/150?img=1", amount: 5000, date: "2026-05-25" },
      { id: "a2", type: "comment", user: "Tunde Bakare", avatar: "https://i.pravatar.cc/150?img=2", message: "This beat is incredible!", date: "2026-05-24" },
      { id: "a3", type: "milestone", user: "System", avatar: "", message: "Reached 75% funding!", date: "2026-05-23" },
    ],
    comments: [
      { id: "c1", user: "Amara Diallo", avatar: "https://i.pravatar.cc/150?img=1", text: "This is exactly what African music needs right now. Pure soul.", likes: 47, date: "2026-05-20" },
      { id: "c2", user: "Tunde Bakare", avatar: "https://i.pravatar.cc/150?img=2", text: "The production quality is insane. Can't wait for the full release!", likes: 32, date: "2026-05-19" },
    ],
    createdAt: "2026-04-25",
  },
  {
    id: "2",
    slug: "lagos-midnight",
    title: "Lagos Midnight",
    artist: "Adaeze Okafor",
    artistId: "adaeze-okafor",
    artistAvatar: "https://i.pravatar.cc/150?img=5",
    coverArt: "https://picsum.photos/seed/lagos2/400/400",
    genre: "Afro-Soul",
    description: "A midnight journey through the streets of Lagos, told through haunting vocals and deep bass.",
    story: "Lagos never sleeps. This song captures the energy of 3am in the city — the street vendors, the lovers, the dreamers.",
    fundingGoal: 750000,
    amountRaised: 612000,
    supporters: 2187,
    daysLeft: 5,
    deadline: "2026-05-31",
    status: "active",
    tags: ["afro-soul", "nigeria", "lagos", "midnight"],
    topSupporters: [
      { id: "s4", name: "Chidi Nwosu", avatar: "https://i.pravatar.cc/150?img=4", amount: 50000, message: "Lagos represent!", date: "2026-05-22" },
    ],
    recentActivity: [
      { id: "a4", type: "support", user: "Chidi Nwosu", avatar: "https://i.pravatar.cc/150?img=4", amount: 10000, date: "2026-05-25" },
    ],
    comments: [
      { id: "c3", user: "Chidi Nwosu", avatar: "https://i.pravatar.cc/150?img=4", text: "This song makes me miss home so much. Beautiful work Adaeze.", likes: 89, date: "2026-05-22" },
    ],
    createdAt: "2026-04-20",
  },
  {
    id: "3",
    slug: "nairobi-sunrise",
    title: "Nairobi Sunrise",
    artist: "Wanjiru Kamau",
    artistId: "wanjiru-kamau",
    artistAvatar: "https://i.pravatar.cc/150?img=9",
    coverArt: "https://picsum.photos/seed/nairobi3/400/400",
    genre: "Gengetone",
    description: "East African street vibes meet global trap production in this Nairobi anthem.",
    story: "Growing up in Eastlands, I always wanted to tell our story. This song is for every kid who hustled from sunrise.",
    fundingGoal: 300000,
    amountRaised: 300000,
    supporters: 987,
    daysLeft: 0,
    deadline: "2026-05-15",
    status: "funded",
    tags: ["gengetone", "kenya", "nairobi", "trap"],
    topSupporters: [],
    recentActivity: [],
    comments: [],
    createdAt: "2026-04-01",
  },
  {
    id: "4",
    slug: "desert-blues",
    title: "Desert Blues",
    artist: "Moussa Traoré",
    artistId: "moussa-traore",
    artistAvatar: "https://i.pravatar.cc/150?img=15",
    coverArt: "https://picsum.photos/seed/desert4/400/400",
    genre: "Afro-Blues",
    description: "Ancient Malian kora melodies fused with contemporary blues guitar.",
    story: "My grandfather played kora under the stars in Timbuktu. I carry his spirit in every note.",
    fundingGoal: 400000,
    amountRaised: 156000,
    supporters: 543,
    daysLeft: 21,
    deadline: "2026-06-16",
    status: "active",
    tags: ["afro-blues", "mali", "kora", "desert"],
    topSupporters: [],
    recentActivity: [],
    comments: [],
    createdAt: "2026-05-05",
  },
  {
    id: "5",
    slug: "cape-town-waves",
    title: "Cape Town Waves",
    artist: "Sipho Dlamini",
    artistId: "sipho-dlamini",
    artistAvatar: "https://i.pravatar.cc/150?img=20",
    coverArt: "https://picsum.photos/seed/capetown5/400/400",
    genre: "Amapiano",
    description: "Log drum rhythms and piano melodies inspired by the Cape Town coastline.",
    story: "The ocean has always been my muse. This song is the sound of waves meeting the dance floor.",
    fundingGoal: 600000,
    amountRaised: 445000,
    supporters: 1876,
    daysLeft: 8,
    deadline: "2026-06-03",
    status: "active",
    tags: ["amapiano", "south-africa", "cape-town", "piano"],
    topSupporters: [],
    recentActivity: [],
    comments: [],
    createdAt: "2026-04-28",
  },
  {
    id: "6",
    slug: "dakar-dreams",
    title: "Dakar Dreams",
    artist: "Fatou Diop",
    artistId: "fatou-diop",
    artistAvatar: "https://i.pravatar.cc/150?img=25",
    coverArt: "https://picsum.photos/seed/dakar6/400/400",
    genre: "Mbalax",
    description: "Senegalese sabar drums meet electronic production in this futuristic Mbalax track.",
    story: "Dakar is the city of dreams. Every corner has a story, every drum has a heartbeat.",
    fundingGoal: 350000,
    amountRaised: 89000,
    supporters: 312,
    daysLeft: 30,
    deadline: "2026-06-25",
    status: "active",
    tags: ["mbalax", "senegal", "dakar", "electronic"],
    topSupporters: [],
    recentActivity: [],
    comments: [],
    createdAt: "2026-05-10",
  },
];

export const mockArtists: Artist[] = [
  {
    id: "kofi-mensah",
    username: "kofi-mensah",
    name: "Kofi Mensah",
    avatar: "https://i.pravatar.cc/150?img=11",
    banner: "https://picsum.photos/seed/kofi-banner/1200/400",
    bio: "Ghanaian producer and vocalist blending traditional rhythms with modern Afrobeats. Based in Accra, creating music that speaks to the African soul.",
    genre: ["Afrobeats", "Highlife", "Afro-Soul"],
    location: "Accra, Ghana",
    verified: true,
    followers: 45200,
    supporters: 3421,
    totalRaised: 2850000,
    socialLinks: {
      instagram: "@kofi_mensah",
      twitter: "@kofimensah",
      youtube: "KofiMensahMusic",
      spotify: "Kofi Mensah",
    },
    campaigns: [],
  },
  {
    id: "adaeze-okafor",
    username: "adaeze-okafor",
    name: "Adaeze Okafor",
    avatar: "https://i.pravatar.cc/150?img=5",
    banner: "https://picsum.photos/seed/adaeze-banner/1200/400",
    bio: "Lagos-born singer-songwriter with a voice that cuts through the noise. Afro-Soul meets R&B in a way only Lagos can produce.",
    genre: ["Afro-Soul", "R&B", "Afrobeats"],
    location: "Lagos, Nigeria",
    verified: true,
    followers: 89300,
    supporters: 5672,
    totalRaised: 4200000,
    socialLinks: {
      instagram: "@adaeze_music",
      twitter: "@adaezeokafor",
      spotify: "Adaeze Okafor",
    },
    campaigns: [],
  },
  {
    id: "wanjiru-kamau",
    username: "wanjiru-kamau",
    name: "Wanjiru Kamau",
    avatar: "https://i.pravatar.cc/150?img=9",
    banner: "https://picsum.photos/seed/wanjiru-banner/1200/400",
    bio: "Nairobi's finest. Gengetone pioneer bringing East African street culture to the global stage.",
    genre: ["Gengetone", "Trap", "Afro-Hip-Hop"],
    location: "Nairobi, Kenya",
    verified: false,
    followers: 23100,
    supporters: 1234,
    totalRaised: 980000,
    socialLinks: {
      instagram: "@wanjiru_k",
      twitter: "@wanjirukamau",
    },
    campaigns: [],
  },
  {
    id: "moussa-traore",
    username: "moussa-traore",
    name: "Moussa Traoré",
    avatar: "https://i.pravatar.cc/150?img=15",
    banner: "https://picsum.photos/seed/moussa-banner/1200/400",
    bio: "Keeper of the ancient kora tradition, reimagined for the modern world. From Timbuktu to the world stage.",
    genre: ["Afro-Blues", "World Music", "Kora"],
    location: "Bamako, Mali",
    verified: true,
    followers: 31500,
    supporters: 2100,
    totalRaised: 1650000,
    socialLinks: {
      instagram: "@moussa_kora",
      youtube: "MoussaTraoreMusic",
    },
    campaigns: [],
  },
  {
    id: "sipho-dlamini",
    username: "sipho-dlamini",
    name: "Sipho Dlamini",
    avatar: "https://i.pravatar.cc/150?img=20",
    banner: "https://picsum.photos/seed/sipho-banner/1200/400",
    bio: "Amapiano architect from Cape Town. Log drums, piano keys, and ocean breeze — that's my signature.",
    genre: ["Amapiano", "House", "Afro-Electronic"],
    location: "Cape Town, South Africa",
    verified: true,
    followers: 67800,
    supporters: 4321,
    totalRaised: 3100000,
    socialLinks: {
      instagram: "@sipho_amapiano",
      twitter: "@siphodlamini",
      spotify: "Sipho Dlamini",
    },
    campaigns: [],
  },
  {
    id: "fatou-diop",
    username: "fatou-diop",
    name: "Fatou Diop",
    avatar: "https://i.pravatar.cc/150?img=25",
    banner: "https://picsum.photos/seed/fatou-banner/1200/400",
    bio: "Senegalese artist fusing Mbalax tradition with electronic music. Dakar's heartbeat in every track.",
    genre: ["Mbalax", "Electronic", "Afro-Pop"],
    location: "Dakar, Senegal",
    verified: false,
    followers: 18900,
    supporters: 876,
    totalRaised: 520000,
    socialLinks: {
      instagram: "@fatou_diop_music",
    },
    campaigns: [],
  },
];

export const mockGenres: Genre[] = [
  { id: "afrobeats", name: "Afrobeats", icon: "🥁", color: "#1DB954", count: 234 },
  { id: "amapiano", name: "Amapiano", icon: "🎹", color: "#f59e0b", count: 187 },
  { id: "afro-soul", name: "Afro-Soul", icon: "🎵", color: "#8b5cf6", count: 156 },
  { id: "gengetone", name: "Gengetone", icon: "🎤", color: "#ef4444", count: 98 },
  { id: "afro-blues", name: "Afro-Blues", icon: "🎸", color: "#3b82f6", count: 76 },
  { id: "mbalax", name: "Mbalax", icon: "🪘", color: "#ec4899", count: 54 },
  { id: "highlife", name: "Highlife", icon: "🎺", color: "#f97316", count: 112 },
  { id: "afro-hiphop", name: "Afro-Hip-Hop", icon: "🎧", color: "#06b6d4", count: 143 },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Amara Diallo",
    role: "Music Lover, Dakar",
    avatar: "https://i.pravatar.cc/150?img=1",
    text: "Vibefund changed how I connect with African music. I funded Kofi's album before anyone knew him — now he's everywhere. That feeling is priceless.",
    rating: 5,
  },
  {
    id: "t2",
    name: "Tunde Bakare",
    role: "Music Producer, Lagos",
    avatar: "https://i.pravatar.cc/150?img=2",
    text: "As a producer, Vibefund gave me the financial freedom to create without compromise. My supporters are my label now.",
    rating: 5,
  },
  {
    id: "t3",
    name: "Zara Osei",
    role: "Diaspora Fan, London",
    avatar: "https://i.pravatar.cc/150?img=3",
    text: "Living abroad, Vibefund keeps me connected to the music scene back home. I feel like I'm part of the journey.",
    rating: 5,
  },
  {
    id: "t4",
    name: "Chidi Nwosu",
    role: "Tech Entrepreneur, Abuja",
    avatar: "https://i.pravatar.cc/150?img=4",
    text: "I've funded 12 campaigns on Vibefund. The ROI isn't just financial — it's cultural. I'm investing in African heritage.",
    rating: 5,
  },
];

export const mockNotifications: Notification[] = [
  { id: "n1", type: "support", title: "New Supporter!", message: "Amara Diallo supported your campaign with ₦5,000", read: false, date: "2026-05-25", avatar: "https://i.pravatar.cc/150?img=1" },
  { id: "n2", type: "milestone", title: "Milestone Reached!", message: "Your campaign 'Afrobeats in the Rain' reached 75% funding!", read: false, date: "2026-05-24" },
  { id: "n3", type: "comment", title: "New Comment", message: "Tunde Bakare commented on your campaign", read: true, date: "2026-05-23", avatar: "https://i.pravatar.cc/150?img=2" },
  { id: "n4", type: "system", title: "Campaign Approved", message: "Your new campaign has been approved and is now live", read: true, date: "2026-05-22" },
  { id: "n5", type: "support", title: "New Supporter!", message: "Zara Osei supported your campaign with ₦10,000", read: true, date: "2026-05-21", avatar: "https://i.pravatar.cc/150?img=3" },
];

export const mockAdminUsers: AdminUser[] = [
  { id: "u1", name: "Kofi Mensah", email: "kofi@vibefund.com", role: "artist", status: "active", joinDate: "2026-01-15", totalTransactions: 2850000 },
  { id: "u2", name: "Adaeze Okafor", email: "adaeze@vibefund.com", role: "artist", status: "active", joinDate: "2026-02-03", totalTransactions: 4200000 },
  { id: "u3", name: "Amara Diallo", email: "amara@vibefund.com", role: "supporter", status: "active", joinDate: "2026-01-20", totalTransactions: 125000 },
  { id: "u4", name: "Unknown User", email: "unknown@temp.com", role: "supporter", status: "suspended", joinDate: "2026-05-01", totalTransactions: 0 },
  { id: "u5", name: "Wanjiru Kamau", email: "wanjiru@vibefund.com", role: "artist", status: "pending", joinDate: "2026-05-20", totalTransactions: 0 },
];

export const mockAdminCampaigns: AdminCampaign[] = [
  { id: "ac1", title: "Afrobeats in the Rain", artist: "Kofi Mensah", status: "approved", fundingGoal: 500000, amountRaised: 387500, submittedDate: "2026-04-25", reviewedDate: "2026-04-26" },
  { id: "ac2", title: "Lagos Midnight", artist: "Adaeze Okafor", status: "approved", fundingGoal: 750000, amountRaised: 612000, submittedDate: "2026-04-20", reviewedDate: "2026-04-21" },
  { id: "ac3", title: "New Highlife Anthem", artist: "Unknown Artist", status: "pending", fundingGoal: 200000, amountRaised: 0, submittedDate: "2026-05-24" },
  { id: "ac4", title: "Suspicious Track", artist: "Fake Artist", status: "flagged", fundingGoal: 1000000, amountRaised: 0, submittedDate: "2026-05-23" },
];

export const mockEarningsData: ChartData[] = [
  { name: "Jan", value: 120000, prev: 80000 },
  { name: "Feb", value: 185000, prev: 120000 },
  { name: "Mar", value: 145000, prev: 185000 },
  { name: "Apr", value: 290000, prev: 145000 },
  { name: "May", value: 387500, prev: 290000 },
];

export const mockSupportersData: ChartData[] = [
  { name: "Jan", value: 234 },
  { name: "Feb", value: 456 },
  { name: "Mar", value: 389 },
  { name: "Apr", value: 678 },
  { name: "May", value: 1243 },
];

export const communityStats = {
  totalArtists: 12400,
  totalSupporters: 89300,
  totalRaised: "₦2.4B",
  songsLaunched: 3200,
  countriesReached: 54,
  successRate: 78,
};

import type { VerificationRequest, ProductionStage, PaymentMethod, SupportTier } from "@/src/types";

export const mockVerificationRequests: VerificationRequest[] = [
  { id: "v1", artistId: "wanjiru-kamau", artistName: "Wanjiru Kamau", avatar: "https://i.pravatar.cc/150?img=9", phone: "+254712345678", instagramHandle: "@wanjiru_k", twitterHandle: "@wanjirukamau", declaration: true, status: "pending", submittedDate: "2026-05-20" },
  { id: "v2", artistId: "fatou-diop", artistName: "Fatou Diop", avatar: "https://i.pravatar.cc/150?img=25", phone: "+221771234567", instagramHandle: "@fatou_diop_music", twitterHandle: "", declaration: true, status: "pending", submittedDate: "2026-05-22" },
  { id: "v3", artistId: "kofi-mensah", artistName: "Kofi Mensah", avatar: "https://i.pravatar.cc/150?img=11", phone: "+233244123456", instagramHandle: "@kofi_mensah", twitterHandle: "@kofimensah", declaration: true, status: "approved", submittedDate: "2026-01-10" },
];

export const productionStages: ProductionStage[] = [
  { id: "ps1", label: "Campaign Funded", description: "Your campaign reached its funding goal!", status: "completed", date: "2026-05-15" },
  { id: "ps2", label: "Production Begins", description: "Studio sessions booked and production team assembled", status: "completed", date: "2026-05-20" },
  { id: "ps3", label: "Recording", description: "Vocals and instruments being recorded", status: "in-progress", date: "2026-05-26" },
  { id: "ps4", label: "Mixing & Mastering", description: "Professional mixing and mastering in progress", status: "pending" },
  { id: "ps5", label: "Video Shoot", description: "Music video production", status: "pending" },
  { id: "ps6", label: "Video Editing", description: "Post-production and color grading", status: "pending" },
  { id: "ps7", label: "Release", description: "Song drops on all platforms!", status: "pending" },
];

export const paymentMethods: PaymentMethod[] = [
  { id: "card", label: "Debit/Credit Card", icon: "💳", description: "Visa, Mastercard, Verve" },
  { id: "transfer", label: "Bank Transfer", icon: "🏦", description: "Direct bank transfer" },
  { id: "ussd", label: "USSD", icon: "📱", description: "*737# and other codes" },
  { id: "paystack", label: "Paystack", icon: "🟢", description: "Pay with Paystack" },
];

export const supportTiers: SupportTier[] = [
  { amount: 500, label: "Supporter", perk: "Name in credits", color: "#52525b" },
  { amount: 1000, label: "Fan", perk: "Early access + credits", color: "#1DB954" },
  { amount: 5000, label: "Patron", perk: "Exclusive preview + credits + shoutout", color: "#f59e0b" },
  { amount: 10000, label: "Champion", perk: "All above + signed digital artwork", color: "#8b5cf6" },
];

export const liveActivityFeed = [
  { id: "lf1", user: "Samuel O.", avatar: "https://i.pravatar.cc/150?img=30", action: "supported", amount: 5000, song: "Afrobeats in the Rain", time: "2 min ago" },
  { id: "lf2", user: "Anita K.", avatar: "https://i.pravatar.cc/150?img=31", action: "commented", song: "Lagos Midnight", time: "5 min ago" },
  { id: "lf3", user: "Emeka J.", avatar: "https://i.pravatar.cc/150?img=32", action: "supported", amount: 1000, song: "Cape Town Waves", time: "8 min ago" },
  { id: "lf4", user: "Fatima B.", avatar: "https://i.pravatar.cc/150?img=33", action: "supported", amount: 10000, song: "Afrobeats in the Rain", time: "12 min ago" },
  { id: "lf5", user: "Kwame A.", avatar: "https://i.pravatar.cc/150?img=34", action: "shared", song: "Desert Blues", time: "15 min ago" },
  { id: "lf6", user: "Ngozi P.", avatar: "https://i.pravatar.cc/150?img=35", action: "supported", amount: 500, song: "Dakar Dreams", time: "18 min ago" },
];
